const TYPES=[["Agro4esterie","PER"],["AOP Gruyère/Vacherin","Labels"],["Bandes tampon","PER"],["Base PPr (GE)","PER"],["Base PPr (VD)","PER"],["Bétail (GE)","PER"],["Bétail (VD)","PER"],["ClimaCert (OIC)","PER"],["Couverture automne","PER"],["CSP (ressources)","PER"],["DGE conventions LPN","PER"],["Erosion","PER"],["Estivage","PER"],["IMPEX","PER"],["IN SITU","PER"],["IPS BIO","IP-Suisse"],["IPS VIGNE","IP-Suisse"],["Jachère","PER"],["Lait (échantillons)","Labels"],["Lait LRG","Labels"],["PEaux","PER"],["PER Agri + labels","PER"],["PER Arbo/Baies GE","PER"],["PER Arbo/Baies VD","PER"],["PER Maraîchers + labels","PER"],["PER Viticulture","PER"],["Prélèvements (analyses PPh)","PER"],["PestiRed","PER"],["QI VERGER","PER"],["QII ALPAGES","PER"],["QII SAU","PER"],["QII SVBN","PER"],["Qualité Paysage","PER"],["Réseaux","PER"],["SwissGAP","PER"]].map((x,i)=>({id:i+1,name:x[0],group:x[1]}));
const SUPABASE_URL="https://gmwbknxyumpocobceavj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_b1gO_C1m683y_i56q1YjQw_lFXGNp5T";
let sb=null,syncing=false,syncTimer=null;
let farms=JSON.parse(localStorage.getItem("ctrl_agri_farms_v1")||"[]");
let days=JSON.parse(localStorage.getItem("ctrl_agri_days_v1")||"[]"),controls=[],campaign=localStorage.getItem("ctrl_agri_campaign_v91")||"2026",editingId=null;
days=days.map(normalizeDayShape);
function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function fmt(m){m=Number(m)||0;return Math.floor(m/60)+" h "+String(m%60).padStart(2,"0")}
function showPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".nav button").forEach(x=>x.classList.toggle("active",x.dataset.p===id));if(id==="results")renderResults();if(id==="farms")renderFarms();if(id==="export")renderExport()}
function localFarmToDb(f){return {id:f.id,name:f.name,cantonal_no:f.no||null,town:f.town||null,updated_at:f.updatedAt||new Date().toISOString()}}
function dbFarmToLocal(f){return {id:f.id,name:f.name,no:f.cantonal_no||"",town:f.town||"",updatedAt:f.updated_at||new Date().toISOString()}}
function normalizeDayShape(d){d=d||{};return {...d,id:String(d.id||Date.now()),campaign:String(d.campaign||campaign||"2026"),date:d.date||new Date().toISOString().slice(0,10),km:Number(d.km)||0,travel:Number(d.travel!=null?d.travel:d.travelMin)||0,phone:Number(d.phone)||0,meal:(d.meal==="oui"||d.meal===true)?1:(Number(d.meal)||0),controls:Array.isArray(d.controls)?d.controls:[],schemaVersion:Number(d.schemaVersion)||((Array.isArray(d.controls)&&d.controls.every(c=>Array.isArray(c.types)))?2:1)}}
function localDayToDb(d){return {id:d.id,date:d.date,controller_no:(JSON.parse(localStorage.getItem("ctrl_agri_settings_v91")||"{}").no)||null,activity_kind:"Contrôle",travel_min:Number(d.travel)||0,km:Number(d.km)||0,meal:String(d.meal||0),phone:Number(d.phone)||0,misc_expenses:0,note:JSON.stringify({campaign:d.campaign||campaign,validated:true,schemaVersion:d.schemaVersion||2}),controls:d.controls||[],updated_at:d.updatedAt||new Date().toISOString()}}
function dbDayToLocal(d){let meta={};try{meta=JSON.parse(d.note||"{}")}catch(e){}const rawControls=Array.isArray(d.controls)?d.controls:[];const isNew=rawControls.every(c=>Array.isArray(c.types));return normalizeDayShape({id:d.id,campaign:meta.campaign||campaign,date:d.date,km:Number(d.km)||0,travel:Number(d.travel_min)||0,phone:Number(d.phone)||0,meal:(d.meal==="oui"||d.meal===1||d.meal==="1")?1:(Number(d.meal)||0),controls:rawControls,schemaVersion:isNew?2:1,updatedAt:d.updated_at||new Date().toISOString()})}
function mergeByUpdated(local,remote){const m=new Map(remote.map(x=>[x.id,x]));local.forEach(l=>{const r=m.get(l.id);if(!r || (Date.parse(l.updatedAt||0)||0)>(Date.parse(r.updatedAt||0)||0))m.set(l.id,l)});return [...m.values()]}
function queueSync(){persistFarms();localStorage.setItem("ctrl_agri_days_v1",JSON.stringify(days));if(!sb||syncing)return;clearTimeout(syncTimer);syncTimer=setTimeout(syncNow,500)}
async function syncNow(){if(!sb||syncing)return;syncing=true;const status=document.getElementById("syncStatus");if(status)status.textContent="Synchronisation…";try{const [rf,rd]=await Promise.all([sb.from("farms").select("*"),sb.from("days").select("*")]);if(rf.error)throw rf.error;if(rd.error)throw rd.error;farms=mergeByUpdated(farms,(rf.data||[]).map(dbFarmToLocal));days=mergeByUpdated(days,(rd.data||[]).map(dbDayToLocal));const uf=farms.length?await sb.from("farms").upsert(farms.map(localFarmToDb),{onConflict:"id"}):{error:null};if(uf.error)throw uf.error;const uploadDays=days.filter(d=>Number(d.schemaVersion)===2&&(d.controls||[]).every(c=>Array.isArray(c.types)));const ud=uploadDays.length?await sb.from("days").upsert(uploadDays.map(localDayToDb),{onConflict:"id"}):{error:null};if(ud.error)throw ud.error;persistFarms();localStorage.setItem("ctrl_agri_days_v1",JSON.stringify(days));renderFarms();renderResults();if(status){status.textContent="Synchronisé automatiquement.";status.style.color="#18794e"}}catch(e){console.error(e);if(status){status.textContent="Synchronisation momentanément indisponible.";status.style.color="#9b6a00"}}finally{syncing=false}}
function persistFarms(){localStorage.setItem("ctrl_agri_farms_v1",JSON.stringify(farms))}
function addFarm(){const name=document.getElementById("farmName").value.trim(),no=document.getElementById("farmNo").value.trim(),town=document.getElementById("farmTown").value.trim();if(!name)return alert("Saisir le nom de l'exploitant.");if(!no)return alert("Saisir le n° cantonal d'exploitation.");farms.push({id:"f"+Date.now(),name,no,town,updatedAt:new Date().toISOString()});persistFarms();queueSync();farmName.value="";farmNo.value="";farmTown.value="";renderFarms();renderControls()}
function deleteFarm(id){if(controls.some(c=>c.farmId===id)||days.some(d=>(d.controls||[]).some(c=>c.farmId===id)))return alert("Cette exploitation est déjà utilisée dans un contrôle et ne peut pas être supprimée.");if(!confirm("Supprimer cette exploitation ?"))return;farms=farms.filter(f=>f.id!==id);persistFarms();queueSync();renderFarms();renderControls()}
function renderFarms(){const el=document.getElementById("farmList");if(!el)return;if(!farms.length){el.innerHTML="<p class='muted'>Aucune exploitation enregistrée.</p>";return}el.innerHTML=`<table class="table"><thead><tr><th>Exploitant</th><th>N° cantonal</th><th>Localité</th><th></th></tr></thead><tbody>`+farms.map(f=>`<tr><td><b>${esc(f.name)}</b></td><td>${esc(f.no||"")}</td><td>${esc(f.town||"")}</td><td><button class="btn danger" onclick="deleteFarm('${f.id}')">Supprimer</button></td></tr>`).join("")+`</tbody></table>`}
function farmOpts(){return "<option value=''>— choisir —</option>"+farms.map(f=>`<option value="${f.id}">${esc(f.name)} — ${esc(f.no)}${f.town?" — "+esc(f.town):""}</option>`).join("")}
function typeOpts(){return "<option value=''>— choisir —</option>"+TYPES.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join("")}
function normalizeControls(list){return (list||[]).map(c=>Array.isArray(c.types)?c:{id:c.id||Date.now()+Math.random(),farmId:c.farmId||"",accompanied:!!c.accompanied,types:[{id:Date.now()+Math.random(),typeId:c.typeId||"",minutes:Number(c.minutes)||0}]})}
function addControl(){controls.push({id:Date.now()+Math.random(),farmId:"",accompanied:false,types:[{id:Date.now()+Math.random(),typeId:"",minutes:0}]});renderControls()}
function removeControl(id){controls=controls.filter(c=>c.id!=id);renderControls()}
function setFarm(id,v){const c=controls.find(x=>x.id==id);if(c)c.farmId=v;renderControls()}
function setAccompanied(id,v){const c=controls.find(x=>x.id==id);if(c)c.accompanied=v;renderControls()}
function addType(controlId){const c=controls.find(x=>x.id==controlId);if(!c)return;c.types.push({id:Date.now()+Math.random(),typeId:"",minutes:0});renderControls()}
function removeType(controlId,typeRowId){const c=controls.find(x=>x.id==controlId);if(!c)return;if(c.types.length<=1)return alert("Il faut conserver au moins un type de contrôle.");c.types=c.types.filter(t=>t.id!=typeRowId);renderControls()}
function setTypeValue(controlId,typeRowId,k,v){const c=controls.find(x=>x.id==controlId);if(!c)return;const r=c.types.find(x=>x.id==typeRowId);if(!r)return;r[k]=k==="minutes"?Math.max(0,Number(v)||0):v;renderControls()}
function addTypeMin(controlId,typeRowId,n){const c=controls.find(x=>x.id==controlId);if(!c)return;const r=c.types.find(x=>x.id==typeRowId);if(!r)return;r.minutes=(Number(r.minutes)||0)+n;renderControls()}
function renderControls(){const el=document.getElementById("controls");controls=normalizeControls(controls);if(!controls.length){el.innerHTML="<p class='muted'>Aucun contrôle ajouté.</p>";updateKpis();return}el.innerHTML=controls.map((c,i)=>{const typeHtml=(c.types||[]).map((r,j)=>{const t=TYPES.find(x=>x.id==r.typeId);return `<div class="typeblock"><div class="typehead"><h3 style="font-size:16px;margin:0">Type de contrôle ${j+1}</h3>${c.types.length>1?`<button class="btn danger" onclick="removeType('${c.id}','${r.id}')">Retirer ce type</button>`:""}</div><div class="grid2"><div><label>Type de contrôle</label><select id="type_${c.id}_${r.id}" onchange="setTypeValue('${c.id}','${r.id}','typeId',this.value)">${typeOpts()}</select>${t?`<div class="info">Affectation automatique : <b>${t.group}</b></div>`:""}</div><div><label>Temps de ce type de contrôle</label><div class="quick"><button onclick="addTypeMin('${c.id}','${r.id}',15)">15 min</button><button onclick="addTypeMin('${c.id}','${r.id}',30)">30 min</button><button onclick="addTypeMin('${c.id}','${r.id}',45)">45 min</button><button onclick="addTypeMin('${c.id}','${r.id}',60)">1 h</button><button onclick="addTypeMin('${c.id}','${r.id}',90)">1 h 30</button><button onclick="addTypeMin('${c.id}','${r.id}',120)">2 h</button></div><input type="number" min="0" value="${r.minutes||0}" onchange="setTypeValue('${c.id}','${r.id}','minutes',this.value)"><div><b>${fmt(r.minutes)}</b></div></div></div></div>`}).join("");return `<div class="controlbox"><div class="controlhead"><h3>Contrôle ${i+1}</h3><button class="btn danger" onclick="removeControl('${c.id}')">Supprimer ce contrôle</button></div><div style="max-width:520px"><label>Exploitation</label><select id="farm_${c.id}" onchange="setFarm('${c.id}',this.value)">${farmOpts()}</select></div><div style="margin-top:14px">${typeHtml}</div><div class="actions"><button class="btn secondary" onclick="addType('${c.id}')">＋ Ajouter un type de contrôle</button></div><label style="margin-top:12px"><input type="checkbox" style="width:auto" ${c.accompanied?"checked":""} onchange="setAccompanied('${c.id}',this.checked)"> &nbsp; Contrôle accompagné</label></div>`}).join("");controls.forEach(c=>{const farm=document.getElementById("farm_"+c.id);if(farm)farm.value=c.farmId||"";(c.types||[]).forEach(r=>{const s=document.getElementById("type_"+c.id+"_"+r.id);if(s)s.value=r.typeId||""})});updateKpis()}
function updateKpis(){let s={"PER":0,"Labels":0,"IP-Suisse":0};controls.forEach(c=>(c.types||[]).forEach(r=>{let t=TYPES.find(x=>x.id==r.typeId);if(t)s[t.group]+=Number(r.minutes)||0}));perKpi.textContent=fmt(s.PER);labKpi.textContent=fmt(s.Labels);ipKpi.textContent=fmt(s["IP-Suisse"])}
function addTravel(n){travelMin.value=(Number(travelMin.value)||0)+n}
function resetDay(){editingId=null;dayDate.value=new Date().toISOString().slice(0,10);km.value=travelMin.value=phone.value=0;meal.value=0;controls=[];addControl()}
function validateDay(){if(!dayDate.value)return alert("Choisir la date.");if(!controls.length)return alert("Ajouter au moins un contrôle.");controls=normalizeControls(controls);for(let i=0;i<controls.length;i++){const c=controls[i];if(!c.farmId)return alert("Choisir l'exploitation du contrôle "+(i+1)+".");if(!c.types.length)return alert("Ajouter au moins un type de contrôle au contrôle "+(i+1)+".");for(let j=0;j<c.types.length;j++){const r=c.types[j];if(!r.typeId||Number(r.minutes)<=0)return alert("Compléter le type de contrôle "+(j+1)+" du contrôle "+(i+1)+".")}}if(!confirm("Valider la journée du "+dayDate.value+" ?"))return;let d={id:editingId||Date.now().toString(),campaign,date:dayDate.value,km:Number(km.value)||0,travel:Number(travelMin.value)||0,phone:Number(phone.value)||0,meal:Number(meal.value)||0,controls:JSON.parse(JSON.stringify(controls)),schemaVersion:2,updatedAt:new Date().toISOString()};let ix=days.findIndex(x=>x.id===d.id);if(ix>=0)days[ix]=d;else days.push(d);localStorage.setItem("ctrl_agri_days_v1",JSON.stringify(days));queueSync();editingId=null;alert("Journée validée.");showPage("results")}
function renderResults(){let list=days.filter(d=>d.campaign===campaign).sort((a,b)=>b.date.localeCompare(a.date)),tc=0,tt=0;list.forEach(d=>{tt+=Number(d.travel)||0;if(Number(d.schemaVersion)===2)(normalizeControls(d.controls)||[]).forEach(c=>(c.types||[]).forEach(r=>tc+=Number(r.minutes)||0))});totalControl.textContent=fmt(tc);totalTravel.textContent=fmt(tt);dayList.innerHTML=list.map(d=>{if(Number(d.schemaVersion)!==2)return `<div class="card"><h3>${d.date} <span class="smallbadge">ARCHIVE V9</span></h3><p class="muted">Journée conservée de l’ancienne version. Déplacement ${fmt(d.travel)} · ${d.km} km.</p></div>`;let s={"PER":0,"Labels":0,"IP-Suisse":0},groups=normalizeControls(d.controls);groups.forEach(c=>(c.types||[]).forEach(r=>{let t=TYPES.find(x=>x.id==r.typeId);if(t)s[t.group]+=Number(r.minutes)||0}));let detail=groups.map((c,i)=>{const f=farms.find(x=>x.id===c.farmId);const lines=(c.types||[]).map(r=>{const t=TYPES.find(x=>x.id==r.typeId);return `${esc(t?.name||"")} — ${fmt(r.minutes)} (${t?.group||""})`}).join("<br>");return `<div class="info"><b>Contrôle ${i+1} — ${esc(f?.name||"Exploitation")}</b><br>${lines}</div>`}).join("");return `<div class="card"><h3>${d.date} <span class="smallbadge">VALIDÉE</span></h3><p>PER <b>${fmt(s.PER)}</b> &nbsp; Labels <b>${fmt(s.Labels)}</b> &nbsp; IP-Suisse <b>${fmt(s["IP-Suisse"])}</b></p>${detail}<p class="muted">Déplacement ${fmt(d.travel)} · ${d.km} km · Repas ${d.meal} · Téléphone CHF ${Number(d.phone||0).toFixed(2)}</p><button class="btn secondary" onclick="editDay('${d.id}')">Corriger la journée</button></div>`}).join("")||"<div class='card muted'>Aucune journée validée.</div>"}
function editDay(id){let d=days.find(x=>x.id===id);if(!d)return;if(Number(d.schemaVersion)!==2)return alert("Cette journée provient de l’ancienne version V9. Elle reste conservée, mais n’est pas modifiable dans cette nouvelle structure.");editingId=id;dayDate.value=d.date;km.value=d.km;travelMin.value=d.travel;phone.value=d.phone;meal.value=d.meal;controls=normalizeControls(JSON.parse(JSON.stringify(d.controls||[])));renderControls();showPage("day")}
function renderExport(){let rows=[];days.filter(d=>d.campaign===campaign&&Number(d.schemaVersion)===2).sort((a,b)=>a.date.localeCompare(b.date)).forEach(d=>{let firstRow=true;normalizeControls(d.controls).forEach(c=>{(c.types||[]).forEach(r=>{let t=TYPES.find(x=>x.id==r.typeId);rows.push(`<tr><td>${d.date}</td><td>${esc(t?.name||"")}</td><td>${r.minutes}</td><td>${firstRow?d.travel:""}</td><td>${firstRow?d.km:""}</td><td>${firstRow?d.meal:""}</td><td>${firstRow?Number(d.phone||0).toFixed(2):""}</td><td><b>${t?.group||""}</b></td></tr>`);firstRow=false})})});exportRows.innerHTML=rows.join("")||"<tr><td colspan='8'>Aucune journée validée.</td></tr>"}
function applyTheme(theme){const root=document.documentElement,themes={blue:{blue:"#1172cf",dark:"#0a437d",ink:"#0d2e56",line:"#bfd9ef",pale:"#eef7ff",green:"#0a7f7d"},terracotta:{blue:"#b96a4f",dark:"#7b4938",ink:"#56372f",line:"#dfc5bb",pale:"#f7eee9",green:"#a45f49"},pastelgreen:{blue:"#77a982",dark:"#4f765b",ink:"#365340",line:"#c7ddce",pale:"#eef7f0",green:"#6f9f7c"}};const t=themes[theme]||themes.blue;Object.entries(t).forEach(([k,v])=>root.style.setProperty("--"+k,v));localStorage.setItem("ctrl_agri_theme_v91",theme);const sel=document.getElementById("themeSelect");if(sel&&sel.value!==theme)sel.value=theme}
function saveSettings(){localStorage.setItem("ctrl_agri_settings_v91",JSON.stringify({name:controllerName.value,no:controllerNo.value,second:secondName.value,secondNo:secondNo.value}));lastSave.textContent=new Date().toLocaleString("fr-CH");alert("Paramètres enregistrés.")}
function changeCampaign(){let y=String(Number(campaignInput.value)||"");if(!y)return;campaign=y;localStorage.setItem("ctrl_agri_campaign_v91",campaign);renderResults();campaignBadge.innerHTML="▣ &nbsp; Campagne active : "+campaign;campaignField.value=campaign;showPage("home")}
const savedSettings=JSON.parse(localStorage.getItem("ctrl_agri_settings_v91")||"{}");if(savedSettings.name!==undefined)controllerName.value=savedSettings.name||"";if(savedSettings.no!==undefined)controllerNo.value=savedSettings.no||"";if(savedSettings.second!==undefined)secondName.value=savedSettings.second||"";if(savedSettings.secondNo!==undefined)secondNo.value=savedSettings.secondNo||"";document.querySelectorAll("#controllerName,#controllerNo,#secondName,#secondNo").forEach(x=>x.addEventListener("input",()=>lastSave.textContent=new Date().toLocaleString("fr-CH")));campaignBadge.innerHTML="▣ &nbsp; Campagne active : "+campaign;campaignField.value=campaign;campaignInput.value=campaign;const savedTheme=localStorage.getItem("ctrl_agri_theme_v91")||"blue";if(document.getElementById("themeSelect"))document.getElementById("themeSelect").value=savedTheme;applyTheme(savedTheme);resetDay();renderFarms();if(window.supabase){sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);syncNow();setInterval(syncNow,5000);window.addEventListener("online",syncNow);document.addEventListener("visibilitychange",()=>{if(!document.hidden)syncNow()})}if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(console.error))}